### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 14

### ISSUE THREAD

**Issue by karolisgrinkevicius** [jxnblk/grid-styled#132]
Getting `Enzyme Internal Error: unknown node with tag 14` where `mount` is used on cloned element node. For instance:

```jsx
...
 mount(React.cloneElement(node))
...
```
Works fine on version 4.

**Comment by guidosreis** [comment]
I'm facing the same issue.
Did you find out a solution? Or simply downgraded to version 4?

**Comment by karolisgrinkevicius** [comment]
I personally downgraded to 4 while this is being fixed.

**Comment by bochen2014** [comment]
got the same issue today. `shallow` is fine

```js
import {mount} from 'enzyme';
import {Box } from 'grid-styled';
mount(<Box/>) ;// unknown node with tag 14
```

**Comment by karolisgrinkevicius** [comment]
Is there any progress on this?

**Comment by ericberens** [comment]
Solved by: https://github.com/airbnb/enzyme/pull/1592

**Comment by karolisgrinkevicius** [comment]
Still getting the same issue `Enzyme Internal Error: unknown node with tag 14` with the following dependencies:
```
├─ enzyme@3.4.4
├─ grid-styled@5.0.2
├─ styled-components@3.3.3
└─ styled-system@3.0.2
```

**Comment by ericberens** [comment]
New versions of

```
enzyme-adapter-react-16
enzyme-adapter-react-16.3
enzyme-adapter-react-16.2
enzyme-adapter-react-16.1
```

need to be released to npm before this will work again.

**Comment by karolisgrinkevicius** [comment]
@ericberens thanks, waiting forward for the release to be happened.

**Comment by karolisgrinkevicius** [comment]
[enzyme-adapter-react-16 v1.3.0](https://www.npmjs.com/package/enzyme-adapter-react-16/v/1.3.0) has fixed an error. Closing the issue.
